language: csharp
solution: Alldigit.IG.TradingFacade.sln
sudo: required
dist: trusty
branches:
  only:
    - master
    - develop
env:
  global:
    - MAJOR=1
    - MINOR=1
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore ./Alldigit.IG.TradingFacade.sln
after_success:
  - nunit-console ./Alldigit.IG.TradingFacade.Tests/bin/Release/Alldigit.IG.TradingFacade.Tests.dll
deploy:
  provider: script
  skip_cleanup: true
  script: /bin/sh versioning.sh
  on:
    branch: master