language: csharp
solution: IgTradingFacade.sln
sudo: required
dist: trusty
branches:
  only:
    - master
    - develop
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore IgTradingFacade.sln
after_script:
  - nunit-console IgTradingFacade.Tests/bin/Release/IgTradingFacade.Tests.dll