language: csharp
solution: IgTradingFacade.sln
branches:
  only:
    - master
    - develop
install:
  - nuget restore IgTradingFacade.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release IgTradingFacade.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./IgTradingFacade.Tests/bin/Release/IgTradingFacade.Tests.dll