language: csharp
solution: Alldigit.IG.TradingFacade.sln
sudo: required
dist: trusty
branches:
  only:
    - master
    - develop
env:
  global:
    - MAJOR=1
    - MINOR=1
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore ./Alldigit.IG.TradingFacade.sln
after_success:
  - nunit-console ./Alldigit.IG.TradingFacade.Tests/bin/Release/Alldigit.IG.TradingFacade.Tests.dll
  - export NEW_VERSION=$(/bin/bash versioning.sh)
  - nuget pack ./Alldigit.IG.TradingFacade.nuspec -Version $NEW_VERSION -IncludeReferencedProjects -Prop Configuration=Release
  - git tag $NEW_VERSION
deploy:
  skip_cleanup: true  
  provider: releases
  api_key: $GITHUB_API_KEY
  on:
    tags: true
    branch: master
after_deploy: nuget push ./*.nupkg $NUGET_API_KEY -Source https://www.nuget.org/api/v2/package