//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IgTradingFacade.Tests.Examples
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExampleMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExampleMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IgTradingFacade.Tests.Examples.ExampleMessages", typeof(ExampleMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;accountId&quot;:&quot;dummyAccountId&quot;,&quot;accountName&quot;:&quot;dummyAccountName&quot;,&quot;preferred&quot;:true,&quot;accountType&quot;:&quot;dummyAccountType&quot;}.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;balance&quot;:11.11,&quot;deposit&quot;:22.22,&quot;profitLoss&quot;:33.33,&quot;available&quot;:44.44}.
        /// </summary>
        internal static string AccountInfo {
            get {
                return ResourceManager.GetString("AccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;accountType&quot;:&quot;dummyAccountType&quot;,&quot;accountInfo&quot;:{&quot;balance&quot;:11.11,&quot;deposit&quot;:22.22,&quot;profitLoss&quot;:33.33,&quot;available&quot;:44.44},&quot;currencyIsoCode&quot;:&quot;dummyCurrencyIsoCode&quot;,&quot;currentAccountId&quot;:&quot;dummyAccountId&quot;,&quot;lightstreamerEndpoint&quot;:&quot;dummyLightstreamerEndpoint&quot;,&quot;accounts&quot;:[{&quot;accountId&quot;:&quot;dummyAccountId0&quot;,&quot;accountName&quot;:&quot;dummyAccountName0&quot;,&quot;preferred&quot;:true,&quot;accountType&quot;:&quot;dummyAccountType0&quot;},{&quot;accountId&quot;:&quot;dummyAccountId1&quot;,&quot;accountName&quot;:&quot;dummyAccountName1&quot;,&quot;preferred&quot;:false,&quot;accountType&quot;:&quot;dummyAccountType1&quot;},{&quot;accountId&quot;:&quot;du [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserAccount {
            get {
                return ResourceManager.GetString("UserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;identifier&quot;:&quot;dummyUsername&quot;,&quot;password&quot;:&quot;dummyPassword&quot;,&quot;encryptedPassword&quot;:true}.
        /// </summary>
        internal static string UserCredentials {
            get {
                return ResourceManager.GetString("UserCredentials", resourceCulture);
            }
        }
    }
}
